# Generated by Django 2.1.2 on 2018-10-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disater', '0002_auto_20181023_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
