# Generated by Django 2.1.2 on 2018-10-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disater', '0003_auto_20181024_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas_affected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('street_number', models.IntegerField()),
            ],
        ),
    ]
