# Generated by Django 2.1.1 on 2018-10-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disater', '0004_areas_affected'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
