# Generated by Django 2.1.1 on 2018-10-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disater', '0005_address_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas_affected',
            name='photo',
            field=models.FileField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
